### ISSUE TITLE
Uncaught exception handling http error 

### ISSUE THREAD

**Issue by altaurog** [marmelab/admin-on-rest#449]
We are working on a client for parse server, which displays some funny behavior around permissions.  When an unauthenticated client attempts to list a class to which it doesn't have access, the parse server returns 400 BAD REQUEST, with the content:  `{code: 119, error: "Permission denied for action find on class _User."}`

This results in the following error on the client:
```
uncaught at handleFetch TypeError: Cannot read property 'map' of undefined
    at http://localhost:3000/static/js/bundle.js:45169:37
    at combination (http://localhost:3000/static/js/bundle.js:38863:30)
    at combination (http://localhost:3000/static/js/bundle.js:38863:30)
    at combination (http://localhost:3000/static/js/bundle.js:38863:30)
    at combination (http://localhost:3000/static/js/bundle.js:38863:30)
    at dispatch (http://localhost:3000/static/js/bundle.js:38323:23)
    at http://localhost:3000/static/js/bundle.js:44782:23
    at http://localhost:3000/static/js/bundle.js:43289:19
    at dispatch (http://localhost:3000/static/js/bundle.js:39018:19)
    at sagaDispatch (http://localhost:3000/static/js/bundle.js:42335:13)
```

We tried catching this in our `HttpClient` and disguising it as a 401, thus:
```
if (status === 400) {                                                 
    console.log('Got 400.  ugh.');                                    
    if (json && json.code === 119) {                                  
        console.log(json);                                            
        console.log('Trying to make it look like a 401');             
        return Promise.reject(new HttpError('401 UNAUTHORIZED', 401));
    }
}
```
but we still get the same error as above.  What's the correct way to indicate http errors?

**Comment by fzaninotto** [comment]
Please use StackOverflow for support. GitHub issues are reserved for bug reports.

**Comment by altaurog** [comment]
Okay, thanks.  Will do.  I did think that an uncaught exception on receipt of a 400 Bad Request was a bug, though.  Is that indeed the expected behavior?

**Comment by fzaninotto** [comment]
Admin-on-rest doesn't speak HTTP. The handling of HTTP errors is the job of the `restClient`, which must `throw` an Error in such cases. Admin-on-rest will display the error message in a notification in that case.

**Comment by altaurog** [comment]
Okay, that makes sense.  We're using the provided `fetchJson` function, with the following lines
```
            if (status < 200 || status >= 300) {
                return Promise.reject(new HttpError((json && json.message) || statusText, status));
            }
```
Is that what you mean by `throw`?  In any case, it results in the uncaught exception, above, which we see in the js console.  Is that what you mean by notification?

**Comment by fzaninotto** [comment]
yes, sorry, I meant `reject`.

**Comment by altaurog** [comment]
An uncaught exception is the expected behavior in that case?

**Comment by fzaninotto** [comment]
When you throw an error in asynchronous code instead of returning a rejected promise, yes, it results in an uncaught exception. I don't see what we can do about it.

**Comment by altaurog** [comment]
The `return Promise.reject()` in `fetchJson`, above, results in an uncaught exception.  This occurs when the rest server returned a 400 as I described.

**Comment by fzaninotto** [comment]
I can't reproduce the uncaught exception that you show. I've set up a REST server that returns a 400 on the list route, and all I get in the console is a Bad Request error.

Also, the original exception ('Cannot read property 'map' of undefined') may come from admin-on-rest, but since you have bundled your code without source maps it's impossible to debug.

**Comment by altaurog** [comment]
I don't seem to be able to get proper source maps.  We were using create-react-app, per the tutorial, and  `'cheap-module-source-map'` doesn't seem to do much with chrome.  The best we seem to get is with `'eval'` option:
```
GET https://admin-on-parse.herokuapp.com/parse/classes/_User?limit=10&skip=0 403 (Forbidden)
Error: Forbidden
    at new HttpError (HttpError.js:62)
    at eval (fetch.js:53)
uncaught at handleFetch TypeError: Cannot read property 'map' of undefined
    at eval (webpack:///./~/admin-on-rest/lib/reducer/resource/list/ids.js?:30:36)
    at combination (webpack:///./~/redux/lib/combineReducers.js?:132:29)
    at combination (webpack:///./~/redux/lib/combineReducers.js?:132:29)
    at combination (webpack:///./~/redux/lib/combineReducers.js?:132:29)
    at combination (webpack:///./~/redux/lib/combineReducers.js?:132:29)
    at dispatch (webpack:///./~/redux/lib/createStore.js?:179:22)
    at eval (webpack:///./~/redux-saga/lib/internal/middleware.js?:80:22)
    at eval (webpack:///./~/react-router-redux/lib/middleware.js?:22:18)
    at dispatch (webpack:///./~/redux/lib/applyMiddleware.js?:45:18)
    at sagaDispatch (webpack:///./~/redux-saga/lib/internal/utils.js?:233:12)
```
The error occurs on [line 9 of reducer/resource/list/ids.js](https://github.com/marmelab/admin-on-rest/blob/master/src/reducer/resource/list/ids.js#L9)

With some experimentation, we were able to get our server to return a 403, but note above that even with 403 response we are still getting the same unhandled exception instead of a login screen.

I posted our code [in a gist](https://gist.github.com/altaurog/1475dabf4850db99eef0fd6ad00ab846).

Here's our `package.json`:
```
{
  "name": "test-admin",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "admin-on-rest": "^0.8.4",
    "react": "^15.4.2",
    "react-dom": "^15.4.2"
  },
  "devDependencies": {
    "react-scripts": "0.9.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }
}
```
Which is confirmed by npm:
```
$ npm ls --depth=0
test-admin@0.1.0 /home/altaurog/mokriya/test-admin
├── admin-on-rest@0.8.4
├── parse@1.9.2 extraneous
├── react@15.4.2
├── react-dom@15.4.2
└── react-scripts@0.9.4
```

**Comment by fzaninotto** [comment]
I suggest you start by upgrading to the latest admin-on-rest (0.9)

**Comment by altaurog** [comment]
Thanks.  I ran the initial tutorial instructions again to get a fresh install of the latest versions, but I still have the exact same error:
```
GET https://admin-on-parse.herokuapp.com/parse/classes/_User?limit=10&skip=0 403 (Forbidden)
Error: Forbidden
    at new HttpError (HttpError.js:62)
    at eval (fetch.js:53)
uncaught at handleFetch TypeError: Cannot read property 'map' of undefined
    at eval (webpack:///./~/admin-on-rest/lib/reducer/resource/list/ids.js?:30:36)
    at combination (webpack:///./~/redux/lib/combineReducers.js?:132:29)
    at combination (webpack:///./~/redux/lib/combineReducers.js?:132:29)
    at combination (webpack:///./~/redux/lib/combineReducers.js?:132:29)
    at combination (webpack:///./~/redux/lib/combineReducers.js?:132:29)
    at dispatch (webpack:///./~/redux/lib/createStore.js?:179:22)
    at eval (webpack:///./~/react-router-redux/lib/middleware.js?:22:18)
    at eval (webpack:///./~/redux-saga/lib/internal/middleware.js?:80:22)
    at dispatch (webpack:///./~/redux/lib/applyMiddleware.js?:45:18)
    at sagaDispatch (webpack:///./~/redux-saga/lib/internal/utils.js?:233:12)
```
Could you try our code please?    It's in [this gist](https://gist.github.com/altaurog/1475dabf4850db99eef0fd6ad00ab846).  I imagine if we're doing something wrong, you will be able to find it much more quickly than we would.  Right now I feel like we are running around in circles.

Here's the new `package.json`
```
{
  "name": "admin-on-parse",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "admin-on-rest": "^0.9.2",
    "react": "^15.4.2",
    "react-dom": "^15.4.2"
  },
  "devDependencies": {
    "react-scripts": "0.9.5"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }
}
```
And for the sake of being thorough:
```
$ npm ls --depth=0
admin-on-parse@0.1.0 /home/ubuntu/trill/admin-on-parse                 
├── admin-on-rest@0.9.2                                                
├── react@15.4.2                                                       
├── react-dom@15.4.2                                                   
└── react-scripts@0.9.5                                                
```
Incidentally, is there any way to get better source maps with webpack?  I've tried all the options listed in the devtool documentation, but they don't seem to do much, and none of them actually produce the documented source map notation.

Thanks again for your help.  We're exciting about moving forward with admin-on-rest.

**Comment by fzaninotto** [comment]
Are you aware that the `restClient` response format changed in 0.9 ? See #385.

**Comment by altaurog** [comment]
Thanks for the pointer.  I've updated our code, but it doesn't address the current issue.  The error is raised before `convertHTTPResponseToREST` is called.

**Comment by altaurog** [comment]
Ah.  I see my mistake now.  Sorry to trouble you.

**Comment by chichilatte** [comment]
Note for anyone still experienceing this in 2019...

My custom dataProvider was using `async` functions rather than explicit javascript Promises. When the server returned an error response i caught it (just to log it to the console) and threw the error again. That displayed the "Uncaught error exception" message on screen that the OP was seeing. 

Replacing my `throw err` with a `Promise.reject(err)` did the same thing. I had to rewrite my dataProvider to use promises, just like in the documentation. Too clever for my own good  😏 🔫

**Comment by wattry** [comment]
> Ah. I see my mistake now. Sorry to trouble you.

Mind letting the rest of us know what was wrong?
